## Demonstrating Hive SQL query on spark dataframe...

In [8]:
import pyspark.sql.functions as f
from pyspark.sql import SparkSession

from src import common

In [9]:
spark = common.get_spark_session()

visit_occurrence = spark.read.csv('../data/raw_sample/training/visit_occurrence.csv', header=True)
visit_occurrence.show()

+-----------+----------------+-----------------------------+----------------------+---------+-------------------------+------------+-------------------+------------------+--------------+--------------------+----------------+---------------------------+-----------------------+---------------------+-----------------------+------------------+
|provider_id|visit_start_date|preceding_visit_occurrence_id|admitting_source_value|person_id|discharge_to_source_value|care_site_id|visit_occurrence_id|visit_source_value|visit_end_date|visit_start_datetime|visit_concept_id|admitting_source_concept_id|visit_source_concept_id|visit_type_concept_id|discharge_to_concept_id|visit_end_datetime|
+-----------+----------------+-----------------------------+----------------------+---------+-------------------------+------------+-------------------+------------------+--------------+--------------------+----------------+---------------------------+-----------------------+---------------------+-----------------------+------------------+
|   308053.0|      2008-04-14|                         null|                  null|  57562.0|                     null|     32013.0|            1139153|   887293389050447|    2008-04-14|          2008-04-14|               0|                 44814681.0|                   null|             44818517|                   null|        2008-04-14|
|    66331.0|      2010-05-14|                         null|                  null|  85195.0|                     null|     35869.0|            1352457|   887323387355124|    2010-05-14|          2010-05-14|               0|                 44814675.0|                   null|             44818517|                   null|        2010-05-14|
|    60911.0|      2008-06-23|                         null|                  null| 130925.0|                     null|      4419.0|             503462|   887923388918603|    2008-06-23|          2008-06-23|               0|                       null|                   null|             44818517|                   null|        2008-06-23|
|   165036.0|      2009-12-18|                         null|                  null|  85157.0|                     null|     77179.0|             583750|   887413386907547|    2009-12-18|          2009-12-18|               0|                       null|                   null|             44818517|                   null|        2009-12-18|
|     7087.0|      2008-12-05|                         null|                  null|  85518.0|                     null|      4782.0|            2483589|   887213386442412|    2008-12-05|          2008-12-05|               0|                 44814683.0|                   null|             44818517|                   null|        2008-12-05|
|   457118.0|      2009-12-06|                         null|                  null|  49893.0|                     null|     33207.0|            2403164|   887343389245448|    2009-12-06|          2009-12-06|               0|                 44814675.0|                   null|             44818517|                   null|        2009-12-06|
|   106558.0|      2008-11-23|                         null|                  null|  53694.0|                     null|     23800.0|            2743887|   542802281278752|    2008-11-23|          2008-11-23|            9202|                 44814675.0|                   null|             44818517|             44814705.0|        2008-11-23|
|   419067.0|      2010-01-06|                         null|                  null| 128983.0|                     null|    169103.0|            1545990|   887893386240503|    2010-01-06|          2010-01-06|               0|                 44814681.0|                   null|             44818517|                   null|        2010-01-06|
|   559728.0|      2009-04-01|                         null|                  null|  93767.0|                     null|     18359.0|            3464146|   887323386022733|    2009-04-01|          2009-04-01|               0|                       null|                   null|             44818517|                   null|        2009-04-01|
|   265482.0|      2009-10-15|                         null|                  null|  34002.0|                     null|      4086.0|            4497778|   542112281400407|    2009-10-15|          2009-10-15|            9202|                 44814677.0|                   null|             44818517|                   null|        2009-10-15|
|   176993.0|      2009-02-10|                         null|                  null|  39973.0|                     null|     81832.0|            3108399|   542922281373786|    2009-02-10|          2009-02-10|            9202|                 44814683.0|                   null|             44818517|             44814705.0|        2009-02-10|
|   173763.0|      2009-07-03|                         null|                  null|  81205.0|                     null|     37641.0|             327687|   887563387741243|    2009-07-03|          2009-07-03|               0|                 44814672.0|                   null|             44818517|             44814705.0|        2009-07-03|
|    13435.0|      2010-01-12|                         null|                  null|  56953.0|                     null|      8602.0|             460438|   887103385861168|    2010-01-12|          2010-01-12|               0|                 44814672.0|                   null|             44818517|                   null|        2010-01-12|
|   232786.0|      2008-04-08|                         null|                  null| 105575.0|                     null|      6872.0|            4291974|   542162281421763|    2008-04-08|          2008-04-08|            9202|                 44814683.0|                   null|             44818517|             44814705.0|        2008-04-08|
|   324123.0|      2010-04-16|                         null|                  null|  73378.0|                     null|     30980.0|             898315|   887993388120874|    2010-04-16|          2010-04-16|               0|                 44814681.0|                   null|             44818517|             44814705.0|        2010-04-16|
|   287051.0|      2009-12-05|                         null|                  null|  64892.0|                     null|    122958.0|             717899|   887883387548033|    2009-12-05|          2009-12-05|               0|                 44814672.0|                   null|             44818517|                   null|        2009-12-05|
|   109154.0|      2009-02-10|                         null|                  null|  85323.0|                     null|      6042.0|            1729224|   887723389035452|    2009-02-10|          2009-02-10|               0|                 44814683.0|                   null|             44818517|                   null|        2009-02-10|
|    95560.0|      2008-10-09|                         null|                  null|  22923.0|                     null|     35618.0|             255899|   887953385299781|    2008-10-09|          2008-10-09|               0|                 44814681.0|                   null|             44818517|                   null|        2008-10-09|
|    73518.0|      2008-04-24|                         null|                  null| 134767.0|                     null|      3567.0|            3418331|   542762281450254|    2008-04-24|          2008-04-24|            9202|                 44814672.0|                   null|             44818517|             44814705.0|        2008-04-24|
|   101659.0|      2008-09-14|                         null|                  null|  22332.0|                     null|     51545.0|            1443746|   887823388763676|    2008-09-14|          2008-09-14|               0|                 44814681.0|                   null|             44818517|                   null|        2008-09-14|
+-----------+----------------+-----------------------------+----------------------+---------+-------------------------+------------+-------------------+------------------+--------------+--------------------+----------------+---------------------------+-----------------------+---------------------+-----------------------+------------------+
only showing top 20 rows

Create/replace a temp view. Then use `spark.sql` function to query that view and execute SQL on DataFrame...

In [10]:
visit_occurrence.createOrReplaceTempView("visit_occurrence")

new_df = spark.sql("select person_id,visit_start_date from visit_occurrence limit 3")
new_df.show()

+---------+----------------+
|person_id|visit_start_date|
+---------+----------------+
|  57562.0|      2008-04-14|
|  85195.0|      2010-05-14|
| 130925.0|      2008-06-23|
+---------+----------------+